package: poll
version: '1.1'
author: Friends Of REDAXO
supportpage: www.github.org/friendsofredaxo/poll

page:
    title: translate:poll_settings
    pjax: true
    block: poll
    icon: rex-icon fa-hand-spock-o
    subpages:
        main: { title: 'translate:poll_settings' }
        statistic: { title: 'translate:poll_statistic' }

requires:
    packages:
        yform: '^2.2'
    redaxo: '^5.3'
