package: poll
version: '2.0.0-beta1'
author: Friends Of REDAXO
supportpage: https://github.com/friendsofredaxo/poll

page:
    title: translate:poll_statistic
    pjax: true
    block: poll
    icon: rex-icon fa-hand-spock-o
    perm: poll[]
    subpages:
#        main: { title: 'translate:poll_settings' }
        statistic: { title: 'translate:poll_statistic' }

requires:
    packages:
        yform: '>4'
    redaxo: '^5.3'
