package: poll
version: '2.0.0'
author: Friends Of REDAXO
supportpage: https://github.com/friendsofredaxo/poll

page:
    title: translate:poll_dashboard
    pjax: true
    block: poll
    icon: rex-icon fa-hand-spock-o
    perm: poll[]
    subpages:
        dashboard: { title: 'translate:poll_dashboard' }
        sample: { title: 'translate:poll_sample_data' }

requires:
    packages:
        yform: '>4'
    redaxo: '^5.16.1'
    php:
        version: '>=8.1, <9'
